### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by AlicanC** [kriskowal/gtor#39]
I jumped in to fix the problem i stated in https://github.com/montagejs/collections/issues/132, but even with `collections@2.0.1` the tests fail:
```
$ npm test

> gtor@0.0.1 test /Users/user/gtor
> jasminum test

/Users/user/gtor/test/behavior-test.js
/Users/user/gtor/test/byte-stream-test.js
/Users/user/gtor/test/observable-test.js
/Users/user/gtor/test/promise-test.js
/Users/user/gtor/test/stream-test.js
/Users/user/gtor/test/task-test.js
❯ describe
❯❯ describe /Users/user/gtor/test/behavior-test.js
❯❯❯ it
❯❯❯ it
❯❯❯ it
❯❯❯ describe index behavior
❯❯❯❯ it produces the given index
❯❯ describe /Users/user/gtor/test/byte-stream-test.js
❯❯❯ describe of
❯❯❯❯ it pumps large byte array into small stream buffer
test never completes
/Users/user/gtor/node_modules/asap/asap.js:45
                throw e;
                      ^
TypeError: object is not a function
    at flush (/Users/user/gtor/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:355:11)
npm ERR! Test failed.  See above for more details.
```

**Comment by timofonic** [comment]
Is this fixed? I'm still yet still trying to understand it, it's amazing and mindbreaking :D

**Comment by kriskowal** [comment]
I have not begun to look into this problem.
